### ISSUE TITLE
404 on installation links

### ISSUE THREAD

**Issue by unhammer** [giellalt/keyboard-smn#1]
* https://giellatekno.uit.no/smndoc/index.html 
* https://giellalt.uit.no/tools/docu-smn-manual.html

**Comment by snomos** [comment]
Kor er dei lenkene refererte/førde opp?

**Comment by unhammer** [comment]
[readme-en](https://github.com/giellalt/keyboard-smn#keyboards-for-the-inari-sami-language)

**Comment by snomos** [comment]
Takk. Ei skikeleg opprydding i tastaturdokumentasjonen, inkl. README-filene står på lista mi. 🙂

**Comment by snomos** [comment]
Fixed in 73d7502f5252925e7d27afb65c0aa595e2f9aafc
